Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    AllowedValues:
      - t2.micro
      - t3.micro
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type.
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId