Mappings:
  CidrBlockMap:
    Vpc: 
      CidrBlock: 10.0.0.0/16


Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap
        - CidrBlockMap
        - Vpc
        - CidrBlock
